# Generated by Django 5.0.3 on 2024-04-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
    ]
