# Generated by Django 5.0.3 on 2024-04-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_file_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_table',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='media/'),
        ),
    ]
