# Generated by Django 5.0.3 on 2024-04-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_file_table_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_table',
            new_name='item',
        ),
    ]
