# Generated by Django 5.0.3 on 2024-05-01 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_category_id_item_created_at_item_subcategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subcategory_id',
            new_name='subcategoryid',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 15, 32, 5, 932034)),
        ),
    ]
