# Generated by Django 5.0.3 on 2024-05-02 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_category_id_item_categoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 48, 0, 591076)),
        ),
    ]
