# Generated by Django 5.0.3 on 2024-05-02 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_item_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categoryid',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subcategoryid',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 17, 17, 37, 910629)),
        ),
    ]
