# Generated by Django 5.0.3 on 2024-05-11 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 11, 6, 22, 557959)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
